from agent_ui_template import agent_ui

from agents.course_outline.video_based_outline.video_search_queries import run_construct_video_search_queries, manual_input_review_video_search_queries
from agents.course_outline.video_based_outline.get_hvac_school_videos import run_get_hvac_school_videos
from agents.course_outline.video_based_outline.classify_and_chunk_videos import run_get_transcripts, run_classify_video, run_chunk_videos
from agents.course_outline.video_based_outline.get_relevant_chunks import run_get_relevant_chunks, manual_input_mark_relevant_videos
from agents.course_outline.video_based_outline.video_based_outlines import run_generate_video_based_outline, manual_input_video_outline_consolidation_comments
from agents.course_outline.video_based_outline.consolidate_video_based_outline import run_propose_consolidated_video_outlines

from agents.course_outline.client_reference_based_outline.client_reference_based_outlines import run_generate_outline_from_client_reference, manual_input_client_reference_consolidation_comments
from agents.course_outline.client_reference_based_outline.consolidate_client_reference_based_outline import run_propose_consolidated_reference_outlines

from agents.course_outline.web_research_based_outline.web_search_queries import run_construct_web_search_queries
from agents.course_outline.web_research_based_outline.web_search_screening import run_web_search_screening
from agents.course_outline.web_research_based_outline.get_article_content import run_fetch_article_content
from agents.course_outline.web_research_based_outline.extract_relevant_info import run_get_relevant_info_from_article
from agents.course_outline.web_research_based_outline.get_research_summary import run_get_research_summary, manual_input_review_research_summary
from agents.course_outline.web_research_based_outline.web_research_based_outline import run_generate_web_research_outline

from agents.course_outline.deep_research.deep_research import run_deep_research
from agents.course_outline.deep_research.deep_research_based_outline import run_generate_deep_research_outline

from agents.course_outline.outline_consolidation.outline_consolidation import run_all_outlines_consolidated_and_review, delete_all_outlines_consolidated_and_review
from agents.course_outline.outline_consolidation.review_and_revise_outline import run_review_and_revise_outline, print_course_outline_before_review, delete_review_and_revise_outline


# --- 1) Define pipeline as sections, each with its own steps ---
pipeline_sections = [
    {
        "section_name": "Section 1: Videos Research",
        "steps": [
            {
                "name": "Video Search Query Generator",
                "func": run_construct_video_search_queries,
                "depends_on": [],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Rough Outline",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 1 minute",
                "description": "Generates search queries to identify relevant HVAC school videos on YouTube.",
            },
            {
                "name": "Manual Review - Video Search Queries",
                "func": manual_input_review_video_search_queries,
                "depends_on": ["Video Search Query Generator"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Rough Outline",
                },
                "instructions": [
                    "**Instructions:**",
                    "- Open the `Rough Outline` tab.",
                    "- Check the `video_search_queries` column.",
                    "- Add, delete, or modify queries to ensure they align closely with the intended topics and audience.",
                    "---",
                    "**Example:**",
                    """- If the query generated by AI is "Basic HVAC troubleshooting," you might refine it to "Basic troubleshooting techniques for residential HVAC systems" to more precisely reflect the intended topic."""
                ],
                "estimated_time": "Manual step",
                "description": "Review and adjust the AI-generated video search queries as needed.",
            },
            {
                "name": "Retrieve HVAC School Videos",
                "func": run_get_hvac_school_videos,
                "depends_on": ["Manual Review - Video Search Queries"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Videos Research",
                },
                "estimated_time": "~ 1 minute",
                "description": "Fetches relevant HVAC school YouTube videos based on the approved search queries and lists them in the `Videos Research` sheet."
            },
            {
                "name": "Retrieve Video Transcripts",
                "func": run_get_transcripts,
                "depends_on": ["Retrieve HVAC School Videos"],
                "args": {
                    "sheet": "sheet",
                    "worksheet": "Videos Research",
                },
                "estimated_time": "~ 10 - 20 minutes",
                "description": "Fetches the complete transcripts for the listed videos and stores them in the `Videos Research` sheet."
            },
            {
                "name": "Check Video Relevance",
                "func": run_classify_video,
                "depends_on": ["Retrieve Video Transcripts"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Videos Research",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash"
                },
                "estimated_time": "~ 10 - 20 minutes",
                "description": "Evaluates each video transcript to classify videos as either relevant or irrelevant based on the course context and audience."
            },
            {
                "name": "Chunk Videos",
                "func": run_chunk_videos,
                "depends_on": ["Check Video Relevance"],
                "args": {
                    "sheet": "sheet",
                    "videos_research_worksheet_name": "Videos Research",
                    "video_chunks_worksheet_name": "Video Chunks",
                    "llm": "gemini_2_flash"
                },
                "estimated_time": "~ 10 - 20 minutes",
                "description": "Segments transcripts of all videos marked as relevant into meaningful chunks and stores them in the `Video Chunks` sheet."
            },
            {
                "name": "Identify Relevant Chunks",
                "func": run_get_relevant_chunks,
                "depends_on": ["Chunk Videos"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Videos Research",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash"
                },
                "estimated_time": "~ 10 - 20 minutes",
                "description": "Analyzes segmented chunks from the previous step and identifies the most relevant ones based on course content and audience criteria."
            },
            {
                "name": "Manual Review - Mark relevant videos",
                "func": manual_input_mark_relevant_videos,
                "depends_on": ["Identify Relevant Chunks"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Videos Research",
                    "skip_manual_step": "skip_manual_step"
                },
                "instructions": [
                    "**Instructions:**",
                    "- Go to the `Videos Research` sheet.",
                    "- Use the AI-generated filter view (a filtered list showing only videos marked relevant by AI).",
                    "- In the `Manual Review` column, enter `Yes` if the video is indeed relevant, or `No` if irrelevant.",
                    "- In the `Used for` column, enter `Just Content` (use transcript content only), `As a video` (include entire video), or leave blank if marked irrelevant.",
                    "---",
                    "**Example:**",
                    """- Video about "HVAC thermostat calibration" might be marked `Yes` and used `Just Content` if the transcript is valuable but video format isn't needed.""",
                    "- Clearly irrelevant videos (e.g., unrelated product reviews) should be marked as `No`.",
                ],
                "estimated_time": "Manual step",
                "description": "Verify and confirm the relevance classification suggested by AI for videos.",
            },
            {
                "name": "Generate Video Based Outlines",
                "func": run_generate_video_based_outline,
                "depends_on": ["Manual Review - Mark relevant videos"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Videos Research",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash"
                },
                "estimated_time": "~ 5 - 10 minutes",
                "description": "Produces outlines from transcripts of videos manually confirmed as relevant."
            },
            {
                "name": "Manual Review - Video Outline Consolidation Comments",
                "func": manual_input_video_outline_consolidation_comments,
                "depends_on": ["Generate Video Based Outlines"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Videos Research",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "skip_manual_step": "skip_manual_step",
                    "llm": "gemini_2_flash",
                },
                "instructions": [
                    "Your task is to add comments to tell the AI how you'd like to consolidate the video based outlines into a single outline.",
                    "- Please review the videos based outlines generated by AI in the `Videos Research` sheet",
                    "- Add comments in the `consolidation_comments` column.",
                    "---",
                    "**Example:**",
                    "- If you disagree with some topic / concept included in the outline for a given row, simply put your comments telling the AI why do you disagree.",
                    "- The above is just an example of what can be put in the comments.",
                    "- Think of these comments as telling the AI how to incorporate all this information present into a single coherent outline.",
                    "---",
                    "NOTE: You need to populate the `consolidation_comments` column for all the rows populated with `outline`."
                ],
                "estimated_time": "Manual step",
                "description": "Provide detailed feedback to guide consolidation of individual video outlines into a unified course outline.",
            },
            {
                "name": "Consolidate Video Based Outlines",
                "func": run_propose_consolidated_video_outlines,
                "depends_on": ["Manual Review - Video Outline Consolidation Comments"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Outline Consolidation",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    # "llm": "gemini_2_flash"
                },
                "estimated_time": "~ 2 minutes",
                "description": "Combines multiple individual outlines into four proposed consolidated outline variations in the `Outline Consolidation` sheet."
            },
        ],
    },
    {
        "section_name": "Section 2: Client References",
        "steps": [
            {
                "name": "Generate Client Reference Based Outlines",
                "func": run_generate_outline_from_client_reference,
                "depends_on": ["Consolidate Video Based Outlines"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Client References",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 5 - 10 minutes",
                "description": "Creates outlines based on client-provided references listed in the `Client References` sheet.",
            },
            {
                "name": "Manual Review - Client References Outline Consolidation Comments",
                "func": manual_input_client_reference_consolidation_comments,
                "depends_on": ["Generate Client Reference Based Outlines"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Client References",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "skip_manual_step": "skip_manual_step",
                    "llm": "gemini_2_flash",
                },
                "instructions": [
                    "Your task is to add comments to tell the AI how you'd like to consolidate the client references based outlines into a single outline.",
                    "- Please review the client references based outlines generated by AI in the `Client References` sheet",
                    "- Add comments in the `consolidation_comments` column.",
                    "---",
                    "**Example:**",
                    "- If you disagree with some topic / concept included in the outline for a given row, simply put your comments telling the AI why do you disagree.",
                    "- The above is just an example of what can be put in the comments.",
                    "- Think of these comments as telling the AI how to incorporate all this information present into a single coherent outline.",
                    "---",
                    "NOTE: You need to populate the `consolidation_comments` column for all the rows populated with `outline`."
                ],
                "estimated_time": "Manual step",
                "description": "Provide detailed comments to guide the consolidation of client reference-based outlines.",
            },
            {
                "name": "Consolidate Client Reference Based Outline",
                "func": run_propose_consolidated_reference_outlines,
                "depends_on": ["Manual Review - Client References Outline Consolidation Comments"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Outline Consolidation",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    # "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 2 minutes",
                "description": "Combines individual client reference outlines into four cohesive outline options stored in the `Outline Consolidation` sheet.",
            },
        ],
    },
    {
        "section_name": "Section 3: Web Research",
        "steps": [
            {
                "name": "Web Search Queries Generator",
                "func": run_construct_web_search_queries,
                "depends_on": ["Consolidate Client Reference Based Outline"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Rough Outline",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 2 minutes",
                "description": "Generates web search queries in the `Rough Outline` sheet to use for searching the web.",
            },
            {
                "name": "Obtain Web Article Links",
                "func": run_web_search_screening,
                "depends_on": ["Web Search Queries Generator"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Preliminary Research",
                    "course_name": "course_name",
                    "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 5 - 10 minutes",
                "description": "Executes web searches using generated queries and lists relevant article links in the `Preliminary Research` sheet.",
            },
            {
                "name": "Fetch Web Article Content",
                "func": run_fetch_article_content,
                "depends_on": ["Obtain Web Article Links"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Preliminary Research",
                },
                "estimated_time": "~ 10 - 20 minutes",
                "description": "Retrieves full content of web articles listed in the Preliminary Research sheet.",
            },
            {
                "name": "Extract Relevant Information from Articles",
                "func": run_get_relevant_info_from_article,
                "depends_on": ["Fetch Web Article Content"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Preliminary Research",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "course_background": "course_background",
                    "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 40 - 60 minutes",
                "description": "Identifies and extracts pertinent content from each article to align with course context and audience.",
            },
            {
                "name": "Generate Research Summaries",
                "func": run_get_research_summary,
                "depends_on": ["Extract Relevant Information from Articles"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Rough Outline",
                    "course_name": "course_name",
                    "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 5 - 10 minutes",
                "description": "Summarizes extracted information from web articles into concise, relevant summaries stored in the `Rough Outline` sheet.",
            },
            {
                "name": "Manual Review - Web Research Summary",
                "func": manual_input_review_research_summary,
                "depends_on": ["Generate Research Summaries"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Rough Outline",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "skip_manual_step": "skip_manual_step",
                    "llm": "gemini_2_flash",
                },
                "instructions": [
                    "Your task is to populate the `Manual Extract` column in the `Rough Outline` sheet.",
                    "- Open the `Rough Outline` sheet.",
                    "- Copy summaries from `research_summary` to `Manual Extract`.",
                    "Modify text as necessary (additions, deletions, edits) to finalize accurate summaries.",
                    "---",
                    "**Example:**",
                    "- For example, if you disagree with some topic / concept included in the summary for a given row, simply delete that part.",
                    "- The above is just an example of the kind of edits to make.",
                    "- The info present in `Manual Extract` column will be used in the next step to produce web research notes based outline.",
                    "---",
                    "NOTE: You need to populate the `Manual Extract` column for all the rows populated with `research_summary`."
                ],
                "estimated_time": "Manual step",
                "description": "Review, edit, and confirm AI-generated summaries, ensuring accuracy and relevancy.",
            },
            {
                "name": "Generate Web Research Based Outline",
                "func": run_generate_web_research_outline,
                "depends_on": ["Manual Review - Web Research Summary"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Outline Consolidation",
                    "course_name": "course_name",
                    "course_background": "course_background",
                    # "llm": "gemini_2_flash",
                },
                "estimated_time": "~ 2 - 4 minutes",
                "description": "Creates a detailed course outline based on refined summaries, storing the output in the `Outline Consolidation` sheet.",
            },
        ],
    },
    {
        "section_name": "Section 4: Deep Research",
        "steps": [
            {
                "name": "Deep Research",
                "func": run_deep_research,
                "depends_on": ["Generate Web Research Based Outline"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Deep Research",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "pplx_deep_research",
                },
                "estimated_time": "~ 5 - 10 minutes",
                "description": "Creates a new sheet `Deep Research`, performs agentic deep research on the rough outline subtopics and pastes the research into the sheet.",
            },
            {
                "name": "Generate Deep Research Based Outline",
                "func": run_generate_deep_research_outline,
                "depends_on": ["Deep Research"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Outline Consolidation",
                    "course_name": "course_name",
                    "course_background": "course_background",
                    "llm": "gemini_2_flash_thinking",
                },
                "estimated_time": "~ 5 - 10 minutes",
                "description": "Generates a course outline based on the deep research findings and saves it to a new sheet.",
            },
        ],
    },
    {
        "section_name": "Section 5: Outline Consolidation",
        "steps": [
            {
                "name": "Generate Consolidated Outline",
                "func": run_all_outlines_consolidated_and_review,
                "depends_on": ["Generate Deep Research Based Outline"],
                "args": {
                    "sheet": "sheet",
                    "worksheet_name": "Outline Consolidation",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash_thinking",
                },
                "estimated_time": "~ 2 - 4 minutes",
                "description": "Merges all previously created outlines from various sources into one comprehensive consolidated outline in the `Outline Review` sheet.",
                "delete_func": delete_all_outlines_consolidated_and_review,
                "delete_args": {
                    "sheet": "sheet",
                    "worksheet_name": "Outline Consolidation"
                }
            },
            {
                "name": "Review and Revise Outline",
                "func": run_review_and_revise_outline,
                "depends_on": ["Generate Consolidated Outline"],
                "args": {
                    "sheet": "sheet",
                    "course_name": "course_name",
                    "target_audience": "target_audience",
                    "llm": "gemini_2_flash_thinking",
                    "skip_manual_step": "skip_manual_step"
                },
                "instructions": [
                    "In this step, you can collaborate with the AI to review and revise the course outline pasted in the `Outline Review` sheet. Follow the below steps:",
                    "- Please review the outline generated by AI in the `Outline` column",
                    "- You need to populate these two columns before running this step - `Verdict` and `Manual Feedback`.",
                    "- In the `Verdict` column, say `Approved` if to approve the outline. Else say `Rejected`.",
                    "- If `Rejected`, populate the `Manual Feedback` column with specific comments on what should be changed in the outline.",
                    "---",
                    "**Example:**",
                    "- For example, I can say 'Remove section 3 on blower motors as it is not relevant...' or something along these lines.",
                    "- After entering the inputs, click the button to get revised outline.",
                    "---",
                    "NOTE: You need to populate the `Verdict` column and `Manual Feedback` (if rejected) column."
                ],
                "estimated_time": "~ Semi-Automated Step",
                "description": "Review the AI outline in the `Outline Review` sheet. Add comments in the `Verdict` (valid options are Approved / Rejected) and in the `Manual Feedback` column.",
                "pre_exec_func": print_course_outline_before_review,
                "pre_exec_args": {
                    "sheet": "sheet",
                    "worksheet_name": "Outline Review",
                },
                "delete_func": delete_review_and_revise_outline,
                "delete_args": {
                    "sheet": "sheet",
                }
            },
        ],
    },

]


agent_ui(step_name = "Course Outline", pipeline_sections = pipeline_sections)
