# -*- coding: utf-8 -*-
"""Reference_Image_Pool_Creation_Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLL_hnObgjUSy9z00SLOtWMz7xwrI-4Y
"""

# @title Image Scraper Settings { display-mode: "form" }
sheet_url = "https://docs.google.com/spreadsheets/d/1zTnCOYUr6mS3nGT8dCjMWPVGte1lzPIaWReI1WlUvBU/edit?usp=sharing" # @param {type:"string"}
worksheet_name = "Course info"
column_name = "Graphics References"

"""### Install all libraries"""

# !pip install pdfservices-sdk #langchain

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install pydrive2

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install marker-pdf

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q chromadb imagehash cohere

!pip -q install gspread-formatting

"""## Imports"""

import os
import io
import re
import gspread
import tempfile
import pandas as pd
from PIL import Image
from google.colab import auth
from google.auth import default
from google.colab import drive
from google.colab import userdata
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
from pydrive2.files import GoogleDriveFile
from marker.models import create_model_dict
from marker.output import text_from_rendered
from marker.converters.pdf import PdfConverter
from oauth2client.client import GoogleCredentials
from gspread_formatting.functions import rowcol_to_a1
from oauth2client.service_account import ServiceAccountCredentials
from gspread_formatting import (
    CellFormat,
    TextFormat,
    Color,
    format_cell_range,
    set_row_heights
)

"""## Initial Setup

#### Mount Google Drive and connect to google sheets
"""

## Mounting google drive to read data
drive.mount('/content/drive')

# client_id = userdata.get('OAUTH_CLIENT_ID')
# client_secret = userdata.get('OAUTH_CLIENT_SECRET')

"""#### Oauth"""

# Authenticate once
auth.authenticate_user()

# For PyDrive2 (uses oauth2client)
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Authenticate
auth.authenticate_user()

"""#### Load the logs sheet"""

# Helper to update specific cells in a worksheet
def update_sheet_cell(worksheet, row, col, value):
    worksheet.update_cell(row, col, value)
    print(f"Updated cell ({row}, {col}) with value: {value}")

"""### PDF Parser

#### Parse PDF to Markdown
"""

def parse_pdf_to_markdown(pdf_path):
    converter = PdfConverter(
        artifact_dict=create_model_dict(),
    )

    rendered = converter(pdf_path)
    markdown_text, _, images = text_from_rendered(rendered)

    return markdown_text, images

"""#### Create ./pdf_images folder"""

def create_images_folder_in_drive(drive, course_folder_id, folder_name='pdf_images'):
    """
    Create an images folder inside the course folder.

    :param drive: GoogleDrive instance
    :param course_folder_id: Parent folder ID
    :param folder_name: Name of the images folder
    :return: folder ID of created folder
    """
    # Check if folder already exists
    query = f"'{course_folder_id}' in parents and title='{folder_name}' and mimeType='application/vnd.google-apps.folder' and trashed=false"
    file_list = drive.ListFile({'q': query}).GetList()

    if file_list:
        print(f"Folder '{folder_name}' already exists")
        return file_list[0]['id']

    # Create new folder
    folder = drive.CreateFile({
        'title': folder_name,
        'parents': [{'id': course_folder_id}],
        'mimeType': 'application/vnd.google-apps.folder'
    })
    folder.Upload()

    print(f"Created folder '{folder_name}' with ID: {folder['id']}")
    return folder['id']

"""#### Helper Functions"""

def ensure_pdf_images_folder(drive, course_folder_id):
    query = (
        f"title='pdf_images' and "
        f"mimeType='application/vnd.google-apps.folder' and "
        f"'{course_folder_id}' in parents and trashed=false"
    )

    file_list = drive.ListFile({'q': query}).GetList()

    if file_list:
        return file_list[0]['id']

    folder_metadata = {
        'title': 'pdf_images',
        'mimeType': 'application/vnd.google-apps.folder',
        'parents': [{'id': course_folder_id}],
    }

    folder = drive.CreateFile(folder_metadata)
    folder.Upload()
    return folder['id']

def extract_file_id_from_url(drive_url):
    """
    Extract Google Drive file ID from various URL formats.

    :param drive_url: Google Drive URL
    :return: file ID
    """
    patterns = [
        r'/d/([a-zA-Z0-9-_]+)',
        r'id=([a-zA-Z0-9-_]+)',
        r'/file/d/([a-zA-Z0-9-_]+)',
    ]

    for pattern in patterns:
        match = re.search(pattern, drive_url)
        if match:
            return match.group(1)

    # If no pattern matches, assume the input is already a file ID
    return drive_url

def download_pdf_from_drive(drive, pdf_url):
    """
    Download PDF from Google Drive URL to a temporary file.

    :param drive: GoogleDrive instance
    :param pdf_url: Google Drive URL or file ID
    :return: path to downloaded PDF file
    """
    file_id = extract_file_id_from_url(pdf_url)

    # Get the file
    file = drive.CreateFile({'id': file_id})

    # Create a temporary file
    temp_pdf = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
    temp_pdf_path = temp_pdf.name
    temp_pdf.close()

    # Download the file
    file.GetContentFile(temp_pdf_path)

    return temp_pdf_path

def replace_image_links(markdown_text, image_links):
    """
    Replace local image references in markdown with Drive links.
    More aggressive matching approach.
    """
    updated_markdown = markdown_text

    for img_name, drive_link in image_links.items():
        # Get base name without extension
        base_name = os.path.splitext(img_name)[0]

        # Replace ANY occurrence of the image name in parentheses or quotes
        # This is more aggressive but should catch most cases
        updated_markdown = re.sub(
            rf'([(\["\'])([^)\]"\']*?)({re.escape(base_name)}[^)\]"\'/\\]*?)([)\]"\'])',
            rf'\1{drive_link}\4',
            updated_markdown,
            flags=re.IGNORECASE
        )

    return updated_markdown

def upload_markdown_to_drive(drive, markdown_text, course_folder_id, filename='parsed_document.md'):
    """
    Upload markdown file to Google Drive.

    :param drive: GoogleDrive instance
    :param markdown_text: Markdown content
    :param course_folder_id: Parent folder ID
    :param filename: Name for the markdown file
    :return: File ID of uploaded markdown
    """
    # Create temporary markdown file
    temp_md = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.md', encoding='utf-8')
    temp_md.write(markdown_text)
    temp_md.close()

    try:
        # Upload to Drive
        file = drive.CreateFile({
            'title': filename,
            'parents': [{'id': course_folder_id}],
            'mimeType': 'text/markdown'
        })
        file.SetContentFile(temp_md.name)
        file.Upload()

        print(f"Uploaded markdown: {filename} (ID: {file['id']})")
        return file['id']

    finally:
        # Clean up temp file
        os.unlink(temp_md.name)

def upload_images_to_drive(drive, images_dict, images_folder_id):
    """
    Upload images to Google Drive and return mapping of local paths to Drive links.

    :param drive: GoogleDrive instance
    :param images_dict: Dictionary of {image_name: image_data} from parser
    :param images_folder_id: Folder ID where images will be uploaded
    :return: Dictionary mapping image names to Drive URLs
    """
    from PIL import Image
    import io

    image_links = {}

    for img_name, img_data in images_dict.items():
        # Create temporary file path
        temp_img_path = tempfile.mktemp(suffix='.png')  # Always use PNG for safety

        try:
            # Handle PIL Image objects
            if isinstance(img_data, Image.Image):
                # Convert to RGB if necessary (handles RGBA, P, L modes)
                if img_data.mode not in ('RGB', 'L'):
                    img_data = img_data.convert('RGB')

                # Save as PNG (most compatible, no encoding issues)
                img_data.save(temp_img_path, format='PNG')

                # Update filename to .png if it wasn't already
                if not img_name.lower().endswith('.png'):
                    img_name = os.path.splitext(img_name)[0] + '.png'

            else:
                # Handle bytes data
                with open(temp_img_path, 'wb') as f:
                    f.write(img_data)

            # Upload to Drive
            file = drive.CreateFile({
                'title': img_name,
                'parents': [{'id': images_folder_id}]
            })
            file.SetContentFile(temp_img_path)
            file.Upload()

            # Make file shareable (anyone with link can view)
            file.InsertPermission({
                'type': 'anyone',
                'value': 'anyone',
                'role': 'reader'
            })

            # Get shareable link
            drive_link = f"https://drive.google.com/uc?export=view&id={file['id']}"
            image_links[img_name] = drive_link

            print(f"Uploaded: {img_name} -> {drive_link}")

        except Exception as e:
            print(f"Error uploading {img_name}: {e}")
            # Try to continue with other images
            continue

        finally:
            # Clean up temp file
            if os.path.exists(temp_img_path):
                os.unlink(temp_img_path)

    return image_links

def format_worksheet(worksheet):
    """
    Apply the following formatting to the given `worksheet`:
    1) Freeze row 1
    2) Bold row 1
    3) Fill row 1 background color with a light gray
    4) All cells font size 8
    5) All cells vertical alignment = middle
    6) All cells text wrapping = clip
    7) Set rows 2+ to a fixed height of 40
    """

    # 1) Freeze row 1
    worksheet.freeze(rows=1, cols=0)

    # 2) Bold row 1 & 3) Light gray background for row 1
    header_format = CellFormat(
        backgroundColor=Color(0.95, 0.95, 0.95),   # Approx. #E0E0E0
        textFormat=TextFormat(bold=True)
    )
    format_cell_range(worksheet, '1', header_format)

    # 4) All cells font size 8, 5) vertical alignment = middle, 6) text wrapping = clip
    # Determine the entire worksheet range dynamically
    total_rows = worksheet.row_count
    total_cols = worksheet.col_count
    bottom_right_cell = rowcol_to_a1(total_rows, total_cols)  # e.g., "Z1000"
    full_range = f"A1:{bottom_right_cell}"

    all_cells_format = CellFormat(
        textFormat=TextFormat(fontSize=8),
        verticalAlignment='TOP',
        wrapStrategy='CLIP'
    )
    format_cell_range(worksheet, full_range, all_cells_format)

    # 7) Set rows 2 through total_rows to a fixed height of 40
    set_row_heights(worksheet, [(f'2:{total_rows}', 40)])

    print("Sheet formatting completed successfully!")

def create_reference_data_folder(drive_instance, sheet_url, worksheet_name):
    """
    Creates a top-level 'Reference_Image_{worksheet_name}' folder within the sheet's parent folder.
    This folder will house both the consolidated images and the vector store.
    """
    sheet_id = extract_file_id_from_url(sheet_url)
    sheet_file = drive_instance.CreateFile({'id': sheet_id})
    sheet_file.FetchMetadata(fields='parents')
    parent_folder_id = sheet_file.get('parents', [{'id': 'root'}])[0]['id']

    # Updated folder naming to 'Reference_Image' per user request
    folder_name = f"Reference Image"

    # Use the existing create_images_folder_in_drive helper
    reference_folder_id = create_images_folder_in_drive(drive_instance, parent_folder_id, folder_name)
    print(f"✓ Reference Image Folder: {folder_name} (ID: {reference_folder_id})")
    return reference_folder_id

"""#### Run Process pdf to markdown"""

def process_pdf_to_markdown_with_drive(drive, pdf_url, course_folder_id, output_filename='research_notes.md'):
    """
    Complete workflow: Download PDF, parse, upload images and markdown to Drive.

    :param drive: GoogleDrive instance
    :param pdf_url: Google Drive URL or file ID of the PDF
    :param course_folder_id: Course folder ID where output will be saved
    :param output_filename: Name for the output markdown file
    :return: Dictionary with file IDs and paths
    """
    print("Step 1: Downloading PDF from Drive...")
    pdf_path = download_pdf_from_drive(drive, pdf_url)

    try:
        print("Step 2: Parsing PDF to markdown...")
        markdown_text, images = parse_pdf_to_markdown(pdf_path)

        print("Step 3: Creating images folder in Drive...")
        images_folder_id = create_images_folder_in_drive(drive, course_folder_id)

        print("Step 4: Uploading images to Drive...")
        image_links = upload_images_to_drive(drive, images, images_folder_id)

        print("Step 5: Replacing image links in markdown...")
        updated_markdown = replace_image_links(markdown_text, image_links)

        # VERIFICATION
        if updated_markdown == markdown_text:
            print("WARNING: No replacements were made!")
        else:
            print(f"Markdown was modified ({len(updated_markdown) - len(markdown_text)} character difference)")

        # Check if Drive links are actually in the updated markdown
        drive_link_count = updated_markdown.count('drive.google.com')
        print(f"✓ Found {drive_link_count} Drive links in updated markdown")

        print("Step 6: Uploading markdown to Drive...")
        markdown_file_id = upload_markdown_to_drive(drive, updated_markdown, course_folder_id, output_filename)

        print("\nProcess completed successfully!")
        return {
            'markdown_file_id': markdown_file_id,
            'images_folder_id': images_folder_id,
            'image_count': len(image_links),
            'image_links': image_links,
            'output_filename': output_filename  # ← ADD THIS LINE
        }

    finally:
        # Clean up downloaded PDF
        if os.path.exists(pdf_path):
            os.unlink(pdf_path)

def authenticate_gspread():
    """
    Authenticate with Google Sheets API.
    """
    auth.authenticate_user()
    creds, _ = default()
    gc = gspread.authorize(creds)
    return gc

def get_sheet_data_and_df(sheet_url, worksheet_name):
    """
    Open a spreadsheet by URL and return the worksheet and its data as a DataFrame.
    """
    gc = authenticate_gspread()
    spreadsheet = gc.open_by_url(sheet_url)
    worksheet = spreadsheet.worksheet(worksheet_name)
    df = pd.DataFrame(worksheet.get_all_records())
    return worksheet, df

def get_markdown_from_drive(drive, course_folder_id, markdown_filename):
    """
    Read the markdown file from Google Drive.

    :param drive: GoogleDrive instance
    :param course_folder_id: Course folder ID
    :param markdown_filename: Name of the markdown file
    :return: Markdown text content
    """
    # Search for the markdown file in the course folder
    query = f"'{course_folder_id}' in parents and title='{markdown_filename}' and trashed=false"
    file_list = drive.ListFile({'q': query}).GetList()

    if not file_list:
        raise FileNotFoundError(f"Markdown file '{markdown_filename}' not found in course folder")

    file = file_list[0]

    # Download to temporary file
    temp_md = tempfile.NamedTemporaryFile(delete=False, suffix='.md', mode='w+', encoding='utf-8')
    temp_md.close()

    file.GetContentFile(temp_md.name)

    # Read content
    with open(temp_md.name, 'r', encoding='utf-8') as f:
        content = f.read()

    # Clean up
    os.unlink(temp_md.name)

    return content

"""### Validation Helpers (Retained for Scraper)"""

def validate_pdf_in_folder(drive, pdf_url, course_folder_id):
    """
    Validate if a PDF exists in the specified course folder.

    :param drive: GoogleDrive instance
    :param pdf_url: Google Drive URL or file ID of the PDF
    :param course_folder_id: Course folder ID to check
    :return: Tuple (exists: bool, file_id: str or None)
    """
    try:
        # Extract file ID from URL
        file_id = extract_file_id_from_url(pdf_url)

        # Get the file metadata
        file = drive.CreateFile({'id': file_id})
        file.FetchMetadata(fields='parents,title')

        # Check if the file exists
        if not file:
            return False, None

        # Get parent folder IDs
        parents = file.get('parents', [])
        parent_ids = [parent['id'] for parent in parents]

        # Check if course_folder_id is in the parents
        if course_folder_id in parent_ids:
            return True, file_id
        else:
            return False, None

    except Exception as e:
        print(f"Error validating PDF: {str(e)}")
        return False, None

"""#### Check if markdown file in course folder"""

def check_markdown_exists_in_folder(drive, course_folder_id, course_name):
    """
    Check if research_notes.md file exists in the course folder.

    :param drive: GoogleDrive instance
    :param course_folder_id: Course folder ID to check
    :param course_name: Name of the course
    :return: Tuple (exists: bool, file_id: str or None, filename: str or None)
    """
    try:
        # Search for markdown files in the folder
        query = f"'{course_folder_id}' in parents and trashed=false and " \
                f"(title='research_notes.md')"

        file_list = drive.ListFile({'q': query}).GetList()

        if file_list and len(file_list) > 0:
            # Return the first matching file
            return True, file_list[0]['id'], file_list[0]['title']
        else:
            return False, None, None

    except Exception as e:
        print(f"Error checking for markdown file: {str(e)}")
        return False, None, None

def ensure_automation_columns(worksheet, df):
    """
    Ensure 'Automation Status' and 'Course Sheet Link' columns exist in the worksheet.

    :param worksheet: The worksheet object
    :param df: The dataframe
    :return: Updated dataframe with the columns
    """
    columns_added = []

    # Check and add 'Automation Status' column
    if 'Automation Status' not in df.columns:
        headers = worksheet.row_values(1)
        new_col_index = len(headers) + 1
        worksheet.update_cell(1, new_col_index, 'Automation Status')
        df['Automation Status'] = ''
        columns_added.append('Automation Status')

    # Check and add 'Course Sheet Link' column
    if 'Course Sheet Link' not in df.columns:
        headers = worksheet.row_values(1)
        new_col_index = len(headers) + 1
        worksheet.update_cell(1, new_col_index, 'Course Sheet Link')
        df['Course Sheet Link'] = ''
        columns_added.append('Course Sheet Link')

    if columns_added:
        print(f"✓ Added columns: {', '.join(columns_added)}")

    return df

"""#### Update Automation Status"""

def update_automation_status(worksheet, row_index, status, sheet_link=None):
    """
    Update the Automation Status and optionally Course Sheet Link for a specific row.

    :param worksheet: The worksheet object
    :param row_index: Row index in the sheet (1-indexed, accounting for header)
    :param status: Status message to write
    :param sheet_link: Optional course sheet link URL
    """
    headers = worksheet.row_values(1)

    # Find column indices
    try:
        status_col_index = headers.index('Automation Status') + 1
        worksheet.update_cell(row_index, status_col_index, status)
        print(f"✓ Updated Automation Status (Row {row_index}): {status}")
    except ValueError:
        print(f"⚠️ Warning: 'Automation Status' column not found")

    # Update Course Sheet Link if provided
    if sheet_link:
        try:
            link_col_index = headers.index('Course Sheet Link') + 1
            worksheet.update_cell(row_index, link_col_index, sheet_link)
            print(f"✓ Updated Course Sheet Link (Row {row_index}): {sheet_link}")
        except ValueError:
            print(f"⚠️ Warning: 'Course Sheet Link' column not found")

"""#### Process a single course"""

def process_single_course(drive, gc, row_data, row_index, worksheet,
                         process_pdf_to_markdown_func, populate_research_notes_func):
    """
    Process a single course: validate PDF, convert to markdown, populate research notes.

    :param drive: GoogleDrive instance
    :param gc: gspread client
    :param row_data: Dictionary containing row data (course info)
    :param row_index: Row index in the sheet (1-indexed)
    :param worksheet: The worksheet object
    :param process_pdf_to_markdown_func: Function to process PDF to markdown
    :param populate_research_notes_func: Function to populate research notes
    :return: Dictionary with processing results
    """
    course_name = row_data.get('Name', 'Unknown Course')
    pdf_url = row_data.get('PDF Links', '')
    course_folder_id = row_data.get('Course Folder Drive ID', '')
    lessons = row_data.get('Lesson', '')
    course_sheet_link = row_data.get('Course Sheet Link', '')

    print(f"\n{'=' * 70}")
    print(f"Processing: {course_name}")
    print(f"{'=' * 70}")

    # Check if Course Sheet Link already exists
    if course_sheet_link and course_sheet_link.strip():
        status = "Automation Complete - Course Sheet already exists"
        print(f"✓ {status}")
        print(f"   Course Sheet: {course_sheet_link}")
        return {
            'course_name': course_name,
            'status': 'Already Complete',
            'reason': 'Course Sheet Link already present',
            'spreadsheet_url': course_sheet_link
        }

    # Validation: Check if required fields exist
    if not pdf_url or not pdf_url.strip():
        status = "No PDF link provided"
        update_automation_status(worksheet, row_index, status)
        return {'course_name': course_name, 'status': 'Skipped', 'reason': status}

    if not course_folder_id or not course_folder_id.strip():
        status = "No Course Folder ID provided"
        update_automation_status(worksheet, row_index, status)
        return {'course_name': course_name, 'status': 'Skipped', 'reason': status}

    if not lessons or not lessons.strip():
        status = "No Lessons provided"
        update_automation_status(worksheet, row_index, status)
        return {'course_name': course_name, 'status': 'Skipped', 'reason': status}

    # Step 1: Validate PDF exists in folder
    print(f"\nStep 1: Validating PDF in course folder...")
    pdf_exists, file_id = validate_pdf_in_folder(drive, pdf_url, course_folder_id)

    if not pdf_exists:
        status = "PDF link not in folder"
        update_automation_status(worksheet, row_index, status)
        print(f"❌ {status}")
        return {'course_name': course_name, 'status': 'Failed', 'reason': status}

    print(f"✓ PDF found in folder (File ID: {file_id})")

    # Step 2: Check if markdown file already exists
    print(f"\nStep 2: Checking for existing markdown file...")
    markdown_exists, markdown_file_id, markdown_filename = check_markdown_exists_in_folder(
        drive, course_folder_id, course_name
    )

    try:
        if markdown_exists:
            print(f"✓ Markdown file already exists: {markdown_filename} (ID: {markdown_file_id})")
            print(f"   Skipping PDF to Markdown conversion...")
            markdown_result = {
                'markdown_file_id': markdown_file_id,
                'markdown_filename': markdown_filename,
                'image_count': 0  # We don't know the actual count for existing files
            }
        else:
            # Step 2B: Process PDF to Markdown
            print(f"\nStep 2B: Converting PDF to Markdown...")
            update_automation_status(worksheet, row_index, "Processing: Converting PDF to Markdown")

            markdown_result = process_pdf_to_markdown_func(
                drive=drive,
                pdf_url=pdf_url,
                course_folder_id=course_folder_id,
                output_filename=f'research_notes.md'
            )

            markdown_filename = f'research_notes.md'
            print(f"✓ Markdown file created (ID: {markdown_result['markdown_file_id']})")
            print(f"✓ {markdown_result['image_count']} images uploaded")

        # Step 3: Populate Research Notes
        print(f"\nStep 3: Populating Research Notes...")
        update_automation_status(worksheet, row_index, "Processing: Populating Research Notes")

        # Get the source sheet URL (the sheet we're currently working with)
        source_sheet_url = worksheet.spreadsheet.url

        # Use the existing markdown filename or the newly created one
        markdown_file_to_use = markdown_filename if markdown_exists else f'research_notes.md'

        research_results = populate_research_notes_func(
            drive=drive,
            gc=gc,
            course_folder_id=course_folder_id,
            source_sheet_url=source_sheet_url,
            sheet_name=worksheet.title,
            markdown_filename=markdown_file_to_use
        )

        if research_results and len(research_results) > 0:
            result = research_results[0]
            if result.get('status') == 'Success':
                spreadsheet_url = result.get('spreadsheet_url', '')

                # Update with success status and link
                status = "Course Sheet created with research notes"
                update_automation_status(worksheet, row_index, status, spreadsheet_url)

                print(f"\n✅ Successfully completed: {course_name}")
                print(f"   Course Sheet: {spreadsheet_url}")

                return {
                    'course_name': course_name,
                    'status': 'Success',
                    'spreadsheet_url': spreadsheet_url,
                    'markdown_file_id': markdown_result['markdown_file_id'],
                    'image_count': markdown_result.get('image_count', 0),
                    'markdown_skipped': markdown_exists
                }
            else:
                error_msg = result.get('error', 'Unknown error')
                status = f"Failed: {error_msg}"
                update_automation_status(worksheet, row_index, status)
                return {'course_name': course_name, 'status': 'Failed', 'reason': error_msg}
        else:
            status = "Failed: No research results generated"
            update_automation_status(worksheet, row_index, status)
            return {'course_name': course_name, 'status': 'Failed', 'reason': 'No results'}

    except Exception as e:
        error_msg = str(e)
        status = f"Error: {error_msg[:100]}"  # Limit error message length
        update_automation_status(worksheet, row_index, status)
        print(f"\n Error processing {course_name}: {error_msg}")
        return {'course_name': course_name, 'status': 'Failed', 'reason': error_msg}

# # Step 1: Convert PDF to Markdown
# markdown_result = process_pdf_to_markdown_with_drive(
#     drive=drive,
#     pdf_url=pdf_url,
#     course_folder_id=course_folder_id,
#     output_filename='research_notes.md'
# )

# print(f"✅ Markdown created: {markdown_result['markdown_file_id']}")
# print(f"🖼️  Images: {markdown_result['image_count']}")

"""### Image Scraper Automation
This section contains the logic to extract images from a PDF/PPT and store them in a dedicated Drive folder.
"""

def run_image_scraper(drive_instance, reference_url, parent_for_image_pool_folder_id=None, existing_pool_folder_id=None):
    """
    Downloads a PDF/PPT, extracts images, and stores them in a new or existing Drive folder.
    """
    file_id = extract_file_id_from_url(reference_url)
    file_metadata = drive_instance.CreateFile({'id': file_id})
    file_metadata.FetchMetadata(fields='parents, title')

    print(f"Processing file: {file_metadata['title']}")

    pdf_path = download_pdf_from_drive(drive_instance, file_id)
    try:
        print("Extracting images...")
        _, images = parse_pdf_to_markdown(pdf_path)

        pool_folder_id = existing_pool_folder_id
        if not pool_folder_id:
            if not parent_for_image_pool_folder_id:
                parent_for_image_pool_folder_id = file_metadata.get('parents', [{'id': 'root'}])[0]['id']

            folder_name = "Images"
            pool_folder_id = create_images_folder_in_drive(drive_instance, parent_for_image_pool_folder_id, folder_name)
            print(f"✓ Consolidated 'Images' folder: {pool_folder_id}")

        image_links_map = upload_images_to_drive(drive_instance, images, pool_folder_id)

        return {
            'pool_folder_id': pool_folder_id,
            'pool_folder_url': f"https://drive.google.com/drive/folders/{pool_folder_id}",
            'image_links': image_links_map
        }
    finally:
        if os.path.exists(pdf_path):
            os.unlink(pdf_path)

import pandas as pd

try:
    print(f"Reading sheet: {worksheet_name}...")
    worksheet, df = get_sheet_data_and_df(sheet_url, worksheet_name)

    # Create/Find the top-level 'Reference Data' folder
    reference_data_folder_id = create_reference_data_folder(drive, sheet_url, worksheet_name)

    master_image_pool_folder_id = None
    all_consolidated_image_links = {}
    master_pool_folder_url = ""

    if column_name in df.columns:
        raw_links_series = df[column_name].dropna().astype(str)

        if raw_links_series.empty:
            print(f"❌ Error: No links found in column '{column_name}'.")
        else:
            processed_links_count = 0
            for cell_content in raw_links_series:
                individual_links = [
                    link.strip() for link in cell_content.split('\n')
                    if link.strip() and 'drive.google.com' in link.strip()
                ]

                if not individual_links: continue

                print(f"\nProcessing cell content...")
                for reference_link in individual_links:
                    try:
                        scraper_result = run_image_scraper(
                            drive,
                            reference_link,
                            parent_for_image_pool_folder_id=reference_data_folder_id,
                            existing_pool_folder_id=master_image_pool_folder_id
                        )
                        if not master_image_pool_folder_id:
                            master_image_pool_folder_id = scraper_result['pool_folder_id']
                            master_pool_folder_url = scraper_result['pool_folder_url']

                        all_consolidated_image_links.update(scraper_result['image_links'])
                        processed_links_count += 1
                    except Exception as scraper_e:
                        print(f"  ❌ Error scraping {reference_link}: {scraper_e}")

            if processed_links_count > 0:
                scraper_results = {
                    'reference_data_folder_id': reference_data_folder_id,
                    'pool_folder_id': master_image_pool_folder_id,
                    'pool_folder_url': master_pool_folder_url,
                    'image_links': all_consolidated_image_links
                }
                print(f"\nConsolidated 'Images' folder URL: {scraper_results['pool_folder_url']}")
            else:
                print("\nNo images were processed.")
    else:
        print(f"❌ Column '{column_name}' not found.")

except Exception as e:
    print(f"❌ Main process error: {e}")

"""### Vector Store Implementation
This section implements image embedding using Cohere and vector storage using ChromaDB
"""

import os
import base64
import tempfile
import cohere
import imagehash
import shutil
import time
import uuid
import re
from PIL import Image
from typing import List
from chromadb import Client, Settings

# Initialize Cohere Client (same input expectations)
try:
    COHERE_API_KEY = userdata.get("COHERE_API_KEY")
except Exception:
    COHERE_API_KEY = os.getenv("COHERE_API_KEY")

co = cohere.ClientV2(api_key=COHERE_API_KEY)

def create_vector_store_folder(drive, reference_folder_id):
    """Creates the root 'Vectorstore files' folder inside the Reference Image folder."""
    return create_images_folder_in_drive(drive, reference_folder_id, "Vectorstore files")

def upload_folder_to_drive(local_folder_path, parent_drive_folder_id, drive):
    # Always use 'chroma_graphics_db' as the folder name in Google Drive for consistency
    folder_name = "chroma_graphics_db"

    # Step 1: Create a folder on Drive
    folder_metadata = {
        "title": folder_name,
        "parents": [{"id": parent_drive_folder_id}],
        "mimeType": "application/vnd.google-apps.folder",
    }
    drive_folder = drive.CreateFile(folder_metadata)
    drive_folder.Upload()
    drive_folder_id = drive_folder["id"]

    # Step 2: Recursively upload contents
    for root, dirs, files in os.walk(local_folder_path):
        rel_path = os.path.relpath(root, local_folder_path)
        current_folder_id = drive_folder_id

        # Maintain folder structure
        if rel_path != ".":
            path_parts = rel_path.split(os.sep)
            for part in path_parts:
                folder_list = drive.ListFile({
                    "q": f"title='{part}' and '{current_folder_id}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false"
                }).GetList()
                if folder_list:
                    current_folder_id = folder_list[0]["id"]
                else:
                    subfolder_metadata = {
                        "title": part,
                        "parents": [{"id": current_folder_id}],
                        "mimeType": "application/vnd.google-apps.folder",
                    }
                    subfolder = drive.CreateFile(subfolder_metadata)
                    subfolder.Upload()
                    current_folder_id = subfolder["id"]

        # Upload files in current directory
        for file_name in files:
            file_path = os.path.join(root, file_name)
            f = drive.CreateFile({"title": file_name, "parents": [{"id": current_folder_id}]})
            f.SetContentFile(file_path)
            f.Upload()

def extract_file_id_from_url(url: str) -> str:
    """Extract Drive file id from a standard Drive URL."""
    if not url:
        return ""
    patterns = [
        r"https://drive\.google\.com/file/d/([a-zA-Z0-9_-]+)",
        r"https://drive\.google\.com/open\?id=([a-zA-Z0-9_-]+)",
        r"https://drive\.google\.com/uc\?id=([a-zA-Z0-9_-]+)",
        r"https://drive\.google\.com/uc\?export=download&id=([a-zA-Z0-9_-]+)",
        r"https://drive\.google\.com/uc\?export=view&id=([a-zA-Z0-9_-]+)",
    ]
    for pattern in patterns:
        match = re.match(pattern, url)
        if match:
            return match.group(1)
    return ""


def get_image_embedding(image_path: str) -> List[float]:
    """Generates image embedding using Cohere embed-v4.0."""
    with open(image_path, "rb") as f:
        enc_img = base64.b64encode(f.read()).decode("utf-8")
        enc_img = f"data:image/jpeg;base64,{enc_img}"

    response = co.embed(
        model="embed-v4.0",
        images=[enc_img],
        input_type="image",
        embedding_types=["float"],
    )
    return response.embeddings.float[0]


def get_text_embedding(text: str) -> List[float]:
    """Generates text embedding using Cohere embed-english-v3.0."""
    response = co.embed(
        model="embed-english-v3.0",
        texts=[text],
        input_type="search_document",
        embedding_types=["float"],
    )
    return response.embeddings.float[0]

def build_image_vector_store(drive, image_links, vector_store_drive_id):
    """
    Builds the vector store with simplified hierarchy and uploads to Drive.
    Structure: Vectorstore files -> chroma_graphics_db -> [Chroma Indexing & Data Files]
    Collections: text_embeddings, image_embeddings (compatible with create_vectorstore.py)
    """
    # 1. Setup local paths for the hierarchy
    local_root = f"/tmp/vector_assets_{uuid.uuid4().hex[:8]}"
    db_root = os.path.join(local_root, "chroma_graphics_db")

    if os.path.exists(local_root):
        shutil.rmtree(local_root)

    # Ensure the database root exists
    os.makedirs(db_root, exist_ok=True)

    print(f"Initializing ChromaDB at {db_root}...")

    # Chroma is initialized directly in chroma_graphics_db
    client = Client(Settings(is_persistent=True, persist_directory=db_root))
    text_collection = client.get_or_create_collection(name="text_embeddings")
    image_collection = client.get_or_create_collection(name="image_embeddings")

    print(f"Processing {len(image_links)} images...")

    for img_name, drive_url in image_links.items():
        file_id = extract_file_id_from_url(drive_url)
        if not file_id:
            print(f"❌ Skipping (no file id): {img_name}")
            continue
        success = False

        for attempt in range(4):
            temp_img_path = None
            try:
                temp_img_path = tempfile.mktemp(suffix=".png")
                file = drive.CreateFile({"id": file_id})
                file.GetContentFile(temp_img_path)

                image_embedding = get_image_embedding(temp_img_path)
                text_embedding = get_text_embedding(img_name)

                with Image.open(temp_img_path) as img:
                    phash = str(imagehash.phash(img))

                metadata = {
                    "image_id": file_id,
                    "name": img_name,
                    "drive_url": drive_url,
                    "mime_type": "",
                    "description": img_name,
                    "image_type": "",
                    "image_title": img_name,
                    "folder_id": vector_store_drive_id,
                    "embedding_type": "image",
                    "phash": phash,
                }

                image_collection.add(
                    ids=[f"img_{file_id}"],
                    embeddings=[image_embedding],
                    metadatas=[metadata],
                    documents=["image_embedding_only"],
                )

                text_collection.add(
                    ids=[f"txt_{file_id}"],
                    embeddings=[text_embedding],
                    metadatas=[{**metadata, "embedding_type": "text"}],
                    documents=[img_name],
                )

                print(f"✓ Embedded: {img_name}")
                success = True
                if os.path.exists(temp_img_path):
                    os.unlink(temp_img_path)
                if success:
                    break
            except Exception as e:
                if temp_img_path and os.path.exists(temp_img_path):
                    os.unlink(temp_img_path)
                if "IncompleteRead" in str(e) or "EOF" in str(e):
                    time.sleep(3 * (attempt + 1))
                else:
                    print(f"❌ Failed to embed {img_name}: {e}")
                    break

    print("Uploading structured Vectorstore files to Drive...")
    # Upload everything inside local_root so 'chroma_graphics_db' is the top folder
    upload_folder_to_drive(db_root, vector_store_drive_id, drive)
    print("✅ Hierarchical Vector Store built and uploaded successfully.")

try:
    # 1. Create the Vector Store subfolder
    vector_store_folder_id = create_vector_store_folder(drive, reference_data_folder_id)

    # 2. Build and Upload
    if "scraper_results" in locals() and scraper_results.get("image_links"):
        build_image_vector_store(
            drive,
            scraper_results["image_links"],
            vector_store_folder_id,
        )
    else:
        print("No image links found from the scraper to vectorize.")
except Exception as e:
    print(f"❌ Error in vector store process: {e}")

