"""Generate `sandbox/setup.sh` from the skill's scripts. Run after editing them.

    python build_setup.py            # regenerate
    python build_setup.py --check    # exit 1 if stale (used by selftest.py)

## Why this exists

`mda deploy` syncs `skills/` to Context Hub, and MDA mounts that as a
CompositeBackend *route*. So `read_file /skills/...` works while the shell —
which runs on the sandbox's own disk, the composite's *default* backend — sees
nothing there. Skills are readable but not runnable.

The deployed agent found this immediately and honestly — it ran the right script
with the right arguments, then `find / -name prepare_context_workspace.py` came
back empty.

## Why not the documented mechanism

Deep Agents documents this exact problem ("Execute code with skills") and its
fix: `abefore_agent` middleware calling `self.backend.aupload_files(...)` to
push skill files into the sandbox before the agent runs. That works in OSS
deepagents. It does not work here, for two reasons:

1. `abefore_agent(self, state, runtime)` receives LangGraph's ``Runtime`` —
   state, store, config — and no backend. So the middleware has to *hold* the
   backend, set at construction.
2. MDA builds the ``CompositeBackend`` itself and forbids authors setting
   ``backend``. There is no handle to construct that middleware with.

Worth knowing even if that changes: ``CompositeBackend.aupload_files`` routes by
path, so uploading to ``/skills/...`` would land in the Context Hub mount rather
than on sandbox disk. Files have to go to an unrouted path — like SCRIPTS_DIR —
either way. Only the delivery mechanism differs, not the destination.

Baking trades one cost for another: a script change needs a redeploy, where the
upload approach would not. That is a small price here, since `skills/` only
syncs to Context Hub on deploy anyway.

The fix is to put the scripts where the shell can actually reach them: baked
into the sandbox image at `SCRIPTS_DIR` by `setup.sh`, which runs once at deploy
and is snapshotted for every thread. Embedding them as a base64 tarball keeps
`setup.sh` short and makes the bake deterministic — no clone, no token, no
network dependency at bake time.

Generated rather than hand-maintained because a hand-copied second copy of these
scripts would drift, and drift here is invisible until a deployed run fails.
`--check` is wired into `selftest.py` so editing a script without regenerating
fails offline instead of in production.
"""

from __future__ import annotations

import base64
import gzip
import io
import sys
import tarfile
from pathlib import Path

PROJECT = Path(__file__).resolve().parent
SCRIPTS = PROJECT / "skills" / "working-with-google-sheets" / "scripts"
SETUP = PROJECT / "sandbox" / "setup.sh"

#: Where the scripts land in the sandbox image. Absolute and fixed: the agent
#: should never have to search for them, and `find /` is what it does otherwise.
SCRIPTS_DIR = "/opt/cce/scripts"

HEADER = f'''#!/usr/bin/env bash
# GENERATED by build_setup.py — do not edit. Regenerate after changing any
# script under skills/working-with-google-sheets/scripts/.
#
# Baked once at deploy; every thread sandbox clones the result.
#
# Two jobs:
#
# 1. Dependencies. Deploy-forwarded .env values ARE visible while this runs,
#    which makes it tempting to write a credential here — don't. Whatever lands
#    on disk becomes part of every thread's image, readable by the agent. The
#    auth proxy in sandbox/__init__.py exists precisely so no key needs to be
#    here.
#
# 2. The skill's scripts. `mda deploy` syncs skills/ to Context Hub, which MDA
#    mounts as a backend route — readable with read_file, invisible to the
#    shell, which runs on this disk. So the scripts are baked in here at
#    {SCRIPTS_DIR} instead, and SKILL.md points at that path.
set -e

pip install --break-system-packages -q gspread google-auth pandas

# The image ships python3 but no `python`, and a model reaching for a script
# writes `python` first. One symlink is cheaper than relying on it not to.
if [ ! -e /usr/bin/python ]; then ln -s "$(command -v python3)" /usr/bin/python; fi

mkdir -p {SCRIPTS_DIR}
base64 -d <<'CCE_SCRIPTS_B64' | tar xzf - -C {SCRIPTS_DIR}
'''

FOOTER = f'''CCE_SCRIPTS_B64

chmod -R a+rx {SCRIPTS_DIR}
python3 -c "import sys; sys.path.insert(0, '{SCRIPTS_DIR}'); import _common, _presentation" \\
  && echo "cce scripts baked OK"
'''


def payload() -> str:
    """The scripts as a deterministic base64 gzipped tar.

    Sorted names and pinned mtimes so an unchanged scripts/ regenerates an
    unchanged setup.sh — otherwise `--check` would fail on every run and stop
    meaning anything.
    """
    raw = io.BytesIO()
    # Plain tar here, gzipped separately below: `mode="w:gz"` stamps the current
    # time into the gzip header, so two runs a second apart produce different
    # bytes. That made `--check` pass only when it happened to run in the same
    # second as the generate, which is a check that reports on the clock rather
    # than on the content.
    with tarfile.open(fileobj=raw, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for path in sorted(SCRIPTS.glob("*.py")):
            info = tarfile.TarInfo(name=path.name)
            data = path.read_bytes()
            info.size = len(data)
            info.mtime = 0
            info.mode = 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = "root"
            tar.addfile(info, io.BytesIO(data))
    encoded = base64.b64encode(
        gzip.compress(raw.getvalue(), compresslevel=9, mtime=0)).decode("ascii")
    return "\n".join(encoded[i:i + 76] for i in range(0, len(encoded), 76))


def render() -> str:
    return HEADER + payload() + "\n" + FOOTER


def main() -> int:
    generated = render()
    if "--check" in sys.argv:
        current = SETUP.read_text(encoding="utf-8") if SETUP.exists() else ""
        if current == generated:
            print("sandbox/setup.sh is current")
            return 0
        print("sandbox/setup.sh is STALE — run: python build_setup.py", file=sys.stderr)
        return 1
    SETUP.write_text(generated, encoding="utf-8", newline="\n")
    count = len(list(SCRIPTS.glob("*.py")))
    print(f"wrote {SETUP.relative_to(PROJECT)} embedding {count} scripts "
          f"({len(generated)} bytes) -> {SCRIPTS_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
