from modules.chain import Chain
from tqdm import tqdm
from services.sheets_service import get_sheet_data_and_df, create_or_read_worksheet, save_to_sheet, format_worksheet, clear_worksheet, delete_worksheet, get_worksheet_names
import pandas as pd
from services.helper_functions import get_outline_with_los
from services.smart_progress_bar import SmartProgressBar


outline_consolidation_prompt = """You are tasked with creating a final course outline based on overlapping outlines generated by different agents. Your goal is to produce a coherent, well-structured course outline that effectively covers all necessary topics.

First, review the following course information:

<course_info>
Course Name: <course_name>{course_name}</course_name>

Target Audience: <target_audience>{target_audience}</target_audience>

Tentative Outline:
<tentative_outline>
{tentative_outline}
</tentative_outline>

Required Topic Count:
<required_topic_count>
{required_topic_count}
</required_topic_count>
</course_info>

Now, examine the generated outlines generated by different agents:

<generated_outlines>
{generated_outlines}
</generated_outlines>

Your task is to analyze these partial outlines and create a final, comprehensive course outline. Follow these steps:

1. Analyze the generated outlines:
   - Identify common themes and topics across the outlines
   - Note any contradictions or inconsistencies
   - Recognize the overall structure and flow of the course
   - Compare the generated outlines to the tentative outline provided in the course info
   - Pay attention to any optional user comments or suggestions for the generated outlines

2. Identify the best outline structure:
   - Evaluate which outline(s) cover the concepts most effectively
   - Consider how well each outline aligns with the course name and target audience

3. Combine the outlines:
   - Use the best outline structure as a foundation
   - Merge overlapping content, avoiding duplication
   - Resolve any contradictions by choosing the most logical or frequently mentioned information
   - Incorporate unique concepts from other outlines in a calculated manner
   - Organize the content in a coherent and logical order
   - Ensure all key topics from the partial outlines are included

4. Enforce the required topic count strictly:
   - The course outline must include a specific number of main topics as defined in the Required Topic Count. Follow the rules below carefully to stay within that limit
     a. If a single number is provided (e.g., “8”), generate exactly that number of main topics. You may allow ±1 variation if absolutely unavoidable to maintain logical structure or topic coherence
     b. If a range is provided (e.g., “5–8”), the number of main topics must strictly fall within that range. Do not exceed the upper limit or fall below the lower limit. Strictly do not add or remove topics beyond this range, even if you believe it might improve coverage or flow

5. Create the final course outline:
   - Use the course information to guide the overall structure
   - Incorporate the combined content from the partial outlines
   - Ensure the outline aligns with the course name, target audience, and tentative outline provided in the course info
   - Be detailed with the outline. Use sentences if necessary to explain exactly what is to be covered such that there is no guesswork down the line on what material to include
   - Only include points present in the partial outlines
   - DO NOT add additional points from yourself even if they are present in the tentative outline and not present in partial outlines

Before presenting the final outline, show your thought process inside <outline_synthesis> tags. In this section:
- List and summarize the main topics from each partial outline
- Compare these topics with the tentative outline
- Identify any gaps or inconsistencies
- Create a map of how topics from different outlines relate to each other
- Consider the following questions:
  - How does the best outline compare to the tentative outline?
  - What additions or modifications are necessary to create a comprehensive course outline?
  - How have you ensured that the final outline maintains a logical flow and avoids hindering elements?
  - What unique concepts from other outlines have you incorporated, and why?
  - How many main topics are expected based on the Required Topic Count, and how have you ensured the final outline stays within that range?

It's OK for this section to be quite long.

Present your final course outline using the following format:

<final_outline>
I. Main Topic 1
   A. Subtopic 1
      1. Specific point (Brief explanation if necessary)
      2. Specific point (Brief explanation if necessary)
   B. Subtopic 2
      1. Specific point (Brief explanation if necessary)
      2. Specific point (Brief explanation if necessary)

II. Main Topic 2
   A. Subtopic 1
      1. Specific point (Brief explanation if necessary)
      2. Specific point (Brief explanation if necessary)
   B. Subtopic 2
      1. Specific point (Brief explanation if necessary)
      2. Specific point (Brief explanation if necessary)

[Continue with additional main topics as needed, but remember to stay strictly within the specified required topic count.]
</final_outline>

Remember to maintain a logical flow, ensure comprehensive coverage of the course content, and align the final outline with the provided course information. Your analysis and final outline should demonstrate thorough reasoning and careful consideration of all provided materials.
"""


def outline_consolidation(course_name, target_audience, course_outline, generated_outlines, required_topic_count, llm = 'gemini_2_flash'):
    """
    This function consolidates the generated outlines into a single outline
    Args:
        generated_outlines: generated outlines
        required_topic_count: The topic count required
        llm: llm model to use
    Returns:
        final_outline: final outline
    """
    outline_consolidation_agent = Chain(llm = llm, tags = ["final_outline"])

    outline_consolidation_agent.add_messages(
        [
            ("user", outline_consolidation_prompt.format(
                course_name = course_name,
                target_audience = target_audience,
                tentative_outline = course_outline,
                generated_outlines = generated_outlines,
                required_topic_count=required_topic_count
            ))
        ]
    )

    response = outline_consolidation_agent.run()

    return response["final_outline"]


def run_all_outlines_consolidated_and_review(sheet, worksheet_name, course_name, target_audience, llm='gemini_2_flash'):
    
    _, rough_outline_df = get_sheet_data_and_df(sheet, 'Rough Outline')

    # Fetch Required Topic Count
    _, course_info_df = get_sheet_data_and_df(sheet, "Course info")
    raw_count = course_info_df.loc[0, "Required Topic Count"]
    required_topic_count = str(raw_count).strip() if pd.notna(raw_count) and str(raw_count).strip() else "unspecified"

    # Get the Outline Consolidation Sheet
    outline_consolidation_sheet, outline_consolidation_df = get_sheet_data_and_df(sheet, worksheet_name)
    outline_cols = outline_consolidation_df.columns[1:5]
    
    # Check if consolidated outline already exists
    if 'Consolidated outline' in outline_consolidation_df['Source'].values:
        print('Consolidated outlines already present.')
        return

    # Get the course outline
    course_outline = get_outline_with_los(
        df = rough_outline_df,
        include_learning_objectives = False
    )

    print('Generating consolidated outlines...')
    consolidated_outlines = []

    # Initialize the progress tracker
    progress = SmartProgressBar(total_tasks = 5, description = "Percent complete")

    # Loop through all the columns
    for col in tqdm(outline_cols):
        print(col)

        generated_outlines = ""
        for ind, outline in enumerate(outline_consolidation_df[col].to_list()):
            generated_outlines += f"""<outline id = {ind}>
{outline}
</outline>

"""

        generated_outlines = generated_outlines.strip()

        # Consolidate the outline
        consolidated_outline = outline_consolidation(
            course_name=course_name, 
            target_audience=target_audience, 
            course_outline=course_outline, 
            generated_outlines=generated_outlines, 
            required_topic_count=required_topic_count,
            llm=llm
        )

        consolidated_outlines.append(consolidated_outline)

        print('=' * 50)

        # Update progress
        progress.update()
        
    # **Fix: Ensure Row Length Matches the DataFrame Columns**
    num_columns = len(outline_consolidation_df.columns)
    row_to_add = ['Consolidated outline'] + consolidated_outlines

    # **Pad if Row is Shorter than DataFrame Columns**
    row_to_add += [''] * (num_columns - len(row_to_add))

    # **Ensure Correct Number of Columns Before Adding Row**
    outline_consolidation_df.loc[len(outline_consolidation_df)] = row_to_add[:num_columns]

    # Save to sheet
    save_to_sheet(worksheet = outline_consolidation_sheet, df = outline_consolidation_df)


    ## Get final outline
    sheet_names = [worksheet.title for worksheet in sheet.worksheets()]

    if 'Outline Review' not in sheet_names:
        outline_review_sheet, outline_review_df = create_or_read_worksheet(sheet, 'Outline Review')

        # Get the final consolidated outline
        generated_outlines = ""
        for ind, outline in enumerate(consolidated_outlines):
            generated_outlines += f"""<outline id = {ind}>
{outline}
</outline>

"""
        generated_outlines = generated_outlines.strip()

        consolidated_outline = outline_consolidation(
            course_name=course_name,  
            target_audience=target_audience,  
            course_outline=course_outline,  
            generated_outlines=generated_outlines,  
            required_topic_count=required_topic_count,
            llm=llm
        )

        # Update progress
        progress.update()

        # Create a df
        outline_review_df = pd.DataFrame([
            {
                'Turn': '1',
                'Outline': consolidated_outline,
                'Verdict': '',
                'Manual Feedback': '',
                'AI Suggestions': '',
            }
        ])

        # Save to sheet
        save_to_sheet(worksheet = outline_review_sheet, df = outline_review_df)
        print('Added new sheet and Saved to sheet')

        format_worksheet(worksheet = outline_review_sheet)

    return


def delete_all_outlines_consolidated_and_review(sheet, worksheet_name):
    """
    Deletes the consolidated outline row from the Outline Consolidation sheet and deletes the Outline Review sheet if it exists.
    :param sheet: The Google Sheets object
    :param worksheet_name: Name of the worksheet containing the consolidated outlines
    :return: None    
    """
    # Check if worksheet not already deleted possibly in previous step
    sheet_names = get_worksheet_names(sheet)

    if worksheet_name in sheet_names:
        # Get the Outline Consolidation Sheet
        outline_consolidation_sheet, outline_consolidation_df = get_sheet_data_and_df(sheet, worksheet_name)
        
        # Check if consolidated outline exists
        if 'Consolidated outline' in outline_consolidation_df['Source'].values:
            # Remove the row with 'Consolidated outline'
            outline_consolidation_df = outline_consolidation_df[outline_consolidation_df['Source'] != 'Consolidated outline']
            
            # Clear the worksheet
            clear_worksheet(worksheet = outline_consolidation_sheet)
            
            # Save the updated dataframe back to the sheet
            save_to_sheet(worksheet = outline_consolidation_sheet, df = outline_consolidation_df)
            print(f"Removed 'Consolidated outline' row from {worksheet_name} sheet")
    
    # Check if the Outline Review sheet exists and delete it if it does
    delete_worksheet(sheet = sheet, worksheet_name = 'Outline Review')
    
    return

