[theme]
base="dark"
primaryColor="#f05523"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"

[logger]
# Suppress the "missing ScriptRunContext" warnings from background threads
level = "error"